site_name: Back In Time documentation
site_url: https://backintime-docs.readthedocs.io/
site_author: BIT Team
site_description: Back In Time is a simple backup tool for Linux inspired by "FlyBack".

repo_name: Back In Time
repo_url: https://github.com/bit-team/backintime

theme:
  name: material
  logo: _images/logo48.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
  language: en
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python: 
          show_source: true
          docstring_style: google
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Main Window: main-window.md
  - Settings: settings.md
  - Snapshots Dialog: snapshots-dialog.md
  - Log: log.md
  - Additional: additional.md
